name: Build and Publish C#

on:
  workflow_dispatch:

jobs:
  build_and_publish_csharp:
    runs-on: ubuntu-latest
    env:
      NUGET_TOKEN: ${{ secrets.NUGET_UPLOAD_KEY }}
      PROJECT_NAME: Namu.Serialization
      PROJECT_PATH: Src/Namu.Serialization

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: |
          echo "Building .NET project"
          dotnet build -c Release "./${{ env.PROJECT_PATH }}/${{ env.PROJECT_NAME }}.csproj"

      - name: Pack
        run: |
          echo "Pack"
          dotnet pack -c Release "./${{ env.PROJECT_PATH }}/${{ env.PROJECT_NAME }}.csproj" --output ./nupkg
          
      - name: Publish to NuGet
        run: |
          echo "Publishing to NuGet"          
          dotnet nuget push "./nupkg/${{ env.PROJECT_NAME }}.*.nupkg" --source https://api.nuget.org/v3/index.json --api-key $NUGET_TOKEN
